version: "3.9"  

services:
  bridge:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "80:3000"  # Map port 3000 from container to host
    volumes:
      - ./shared:/shared # Ensure shared folder is mounted correctly
    depends_on:
      - shared
  bot:
    build:
      context: . 
      dockerfile: solidity/Dockerfile  # We'll create this Dockerfile next
    volumes:
      - ./solidity:/app # Mount the solidity directory into the container
      - ./shared:/shared # Ensure shared folder is mounted correctly
    depends_on:
      - shared
    command: ["npx", "hardhat", "run", "scripts/bot.js"]
  shared:
      image: busybox
      volumes:
        - ./shared:/shared