version: "3.9"  

services:
  bridge:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "80:3000"  # Map port 3000 from container to host
    volumes:
      - ./shared:/shared
      - ${SHARED_CONSTANTS_VOLUME}:/app/node_modules/shared/constants
    depends_on:
      - shared
    command: ["sh", "start.sh"]
  bot:
    build:
      context: . 
      dockerfile: solidity/Dockerfile  # We'll create this Dockerfile next
    volumes:
      - ./solidity:/app # Mount the solidity directory into the container
      - ./shared:/shared
      - ${SHARED_CONSTANTS_VOLUME}:/app/node_modules/shared/constants
    depends_on:
      - shared
    command: ["sh", "start.sh"]
    restart: always
  shared:
      image: busybox
      volumes:
        - ./shared:/shared