version: "3.9"  

services:
  nextjs:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 from container to host
    volumes:
      - ./shared:/shared # Ensure shared folder is mounted correctly
    depends_on:
      - shared
  shared:
      image: busybox
      volumes:
        - ./shared:/shared