export const TOKEN_ADDRESS = "0xa00cd6dC7691a22b58f918e2aC3F382f2806D973";
export const TOKEN_ABI = [
  "constructor()",
  "error ERC20InsufficientAllowance(address,uint256,uint256)",
  "error ERC20InsufficientBalance(address,uint256,uint256)",
  "error ERC20InvalidApprover(address)",
  "error ERC20InvalidReceiver(address)",
  "error ERC20InvalidSender(address)",
  "error ERC20InvalidSpender(address)",
  "event Approval(address indexed,address indexed,uint256)",
  "event Transfer(address indexed,address indexed,uint256)",
  "function allowance(address,address) view returns (uint256)",
  "function approve(address,uint256) returns (bool)",
  "function balanceOf(address) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function getMessage() view returns (string)",
  "function mint(address,uint256)",
  "function mint(uint256)",
  "function name() view returns (string)",
  "function setMessage(string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function transfer(address,uint256) returns (bool)",
  "function transferFrom(address,address,uint256) returns (bool)"
];
