import './css/bootstrap.min.css'
import './css/style.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Greenrcoin Swap & Bridge',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Greenrcoin Swap & Bridge</title>
        <meta name="description" content="Source code generated using layoutit.com" />
        <meta name="author" content="LayoutIt!" />
        <link href="css/bootstrap.min.css" rel="stylesheet" />
        <link href="css/style.css" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <div className="container-fluid">
          <div className="row">
            <div className="col-md-3"></div>
            <div className="col-md-6">
              <br /><br />
              {children}
            </div>
            <div className="col-md-3"></div>
          </div>
        </div>
        <script src="js/jquery.min.js" async />
        <script src="js/bootstrap.min.js" async />
        <script src="js/scripts.js" async />
      </body>
    </html>
  )
}
