export const GNC_BRIDGE_ADDRESS = "0x71BAefde114268C3ca5A1C0529B510Cb9B4242EE";
export const GNC_ABI_BRIDGE = [
  "constructor(address)",
  "error EnforcedPause()",
  "error ExpectedPause()",
  "error OwnableInvalidOwner(address)",
  "error OwnableUnauthorizedAccount(address)",
  "error ReentrancyGuardReentrantCall()",
  "event Deposit(address indexed,uint256,bytes32 indexed)",
  "event OwnershipTransferred(address indexed,address indexed)",
  "event Paused(address)",
  "event TransferCompleted(address indexed,uint256,bytes32 indexed)",
  "event Unpaused(address)",
  "function completedTransfers(bytes32) view returns (bool)",
  "function deposit() payable",
  "function getDeposits() view returns ((address,uint256,bytes32)[])",
  "function owner() view returns (address)",
  "function paused() view returns (bool)",
  "function release(address,uint256,bytes32) payable",
  "function removePending(bytes32[])",
  "function renounceOwnership()",
  "function transferOwnership(address)",
  "function withdraw(uint256)",
  "function withdrawTokens(address,uint256)",
  "receive() payable"
];
